<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customers · {{ config('app.name', 'ERP SYSTEM') }}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
    <script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',canvas:'#f4f7fb',muted:'#6d7890'}}}}</script>
</head>
<body class="min-h-screen bg-canvas text-slate-900">
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ url('/') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">ERP SYSTEM</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">
        @foreach ([['/','Home','home'],['/sales','Sales','point_of_sale'],['/products','Products','inventory_2'],['/customers','Customers','groups'],['/suppliers','Suppliers','local_shipping'],['/reimbursements','Reimbursements','receipt_long'],['/purchases','Purchases','shopping_cart'],['/reports','Reports','analytics']] as $item)<a href="{{ url($item[0]) }}" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold {{ $item[1] === 'Customers' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach
    </nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-red-600 hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>
    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-slate-200/70 bg-white/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div class="flex max-w-xl flex-1 items-center gap-3 rounded-xl bg-slate-50 px-4 py-2"><span class="material-symbols-outlined text-muted">search</span><input type="search" placeholder="Search business customers..." class="w-full bg-transparent text-sm outline-none"></div><div class="hidden rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:block">Store workspace · Davao City</div></header>
        <main class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">groups</span><h1 class="text-3xl font-extrabold tracking-tight">Customers</h1></div><p class="mt-2 text-base text-muted">Manage business customer accounts and sales balances.</p></div><button type="button" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-white shadow-md"><span class="material-symbols-outlined">add</span>Add Customer</button></div>
            <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><p class="text-sm text-muted">Business records only. Personal information is not displayed.</p></div><div class="hidden grid-cols-12 gap-4 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-muted lg:grid"><span class="col-span-3">Business</span><span class="col-span-2">Account ID</span><span class="col-span-2">Orders</span><span class="col-span-2">Outstanding</span><span class="col-span-2">Status</span><span>Action</span></div><div class="divide-y divide-slate-100">@foreach ([['Juan Trading','CUS-00125','18 orders','₱2,500.00','Active'],['Davao Grocers','CUS-00124','12 orders','₱0.00','Active'],['Market Basket Retail','CUS-00121','9 orders','₱8,200.00','Review'],['City Pantry Wholesale','CUS-00118','24 orders','₱0.00','Active']] as $customer)<article class="grid grid-cols-1 gap-3 px-5 py-4 lg:grid-cols-12 lg:items-center lg:gap-4"><div class="lg:col-span-3"><p class="font-bold">{{ $customer[0] }}</p><p class="text-xs text-muted">Business customer</p></div><p class="text-sm text-muted lg:col-span-2">{{ $customer[1] }}</p><p class="text-sm lg:col-span-2">{{ $customer[2] }}</p><p class="text-sm font-extrabold lg:col-span-2">{{ $customer[3] }}</p><span class="w-fit rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700 lg:col-span-2">{{ $customer[4] }}</span><button class="w-fit rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-primary">View account</button></article>@endforeach</div></section>
        </main></div>
</body>
</html>
