<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home · {{ config('app.name', 'EasyBiz') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config={theme:{extend:{colors:{ink:'#131b2e',muted:'#656b7e',canvas:'#faf8ff',primary:'#004ac6',soft:'#dbe1ff',secondary:'#006c4a',danger:'#ba1a1a',dangerSoft:'#ffdad6'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-ink antialiased">
    @include('partials.business-directory')
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ route('home') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">EasyBiz</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['home','Home','home'],['sales','Sales','point_of_sale'],['products','Products','inventory_2'],['customers','Customers','groups'],['suppliers','Suppliers','local_shipping'],['reimbursements','Reimbursements','receipt_long'],['purchases','Purchases','shopping_cart'],['reports','Reports','analytics']] as $item)<a href="{{ route($item[0]) }}" class="flex min-h-11 items-center gap-3 rounded-xl px-4 text-sm font-semibold {{ $item[0] === 'home' ? 'bg-primary text-white shadow-sm' : 'text-muted hover:bg-slate-100 hover:text-ink' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-dangerSoft"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>
    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between gap-4 border-b border-slate-200/70 bg-canvas/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div><p class="text-sm font-semibold text-muted">Business overview</p><p class="text-xs text-slate-400">{{ now()->format('l, M j, Y') }}</p></div><div class="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:flex"><span class="material-symbols-outlined text-secondary">store</span>Maria's Store · Davao City</div></header>
        <main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8"><p class="mb-2 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-secondary"><span class="h-2 w-2 rounded-full bg-secondary"></span>Today at a glance</p><h1 class="text-3xl font-extrabold tracking-tight sm:text-4xl">{{ now()->hour < 12 ? 'Good morning' : (now()->hour < 18 ? 'Good afternoon' : 'Good evening') }}! <span class="inline-block animate-bounce" aria-hidden="true">👋</span></h1><p class="mt-2 text-base text-muted">Here’s what’s happening with your business today.</p></div>
            @if ($dashboard['demo'])<div class="mb-8 flex items-start gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-5 text-primary"><span class="material-symbols-outlined">info</span><div><p class="font-bold">Temporary demo data</p><p class="mt-1 text-sm">These sample figures will be replaced automatically when business records are connected.</p></div></div>@endif
            <section class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Today's business summary">@foreach ([['Today’s Sales',$dashboard['todaySales'],'payments','text-primary bg-soft'],['Today’s Expenses',$dashboard['todayExpenses'],'receipt_long','text-slate-600 bg-slate-100'],['Today’s Profit',$dashboard['todayProfit'],'trending_up','text-secondary bg-emerald-100'],['Total Products',$dashboard['products'],'inventory_2','text-primary bg-blue-100']] as $metric)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-muted">{{ $metric[0] }}</span><span class="material-symbols-outlined rounded-xl p-2 {{ $metric[3] }}">{{ $metric[2] }}</span></div><p class="mt-4 text-2xl font-extrabold">{{ $metric[1] === null ? 'Unavailable' : (in_array($metric[0], ['Today’s Sales','Today’s Expenses','Today’s Profit']) ? '₱'.number_format($metric[1], 2) : number_format($metric[1])) }}</p><p class="mt-2 text-xs text-muted">{{ $metric[1] === null ? 'No connected records' : 'Updated from business records' }}</p></article>@endforeach</section>
            <section class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-3" aria-label="Pending work">@foreach ([['Low Stock',$dashboard['lowStock'],'warning',route('products')],['Pending Purchases',$dashboard['pendingPurchases'],'shopping_cart',route('purchases')],['Pending Reimbursements',$dashboard['pendingReimbursements'],'receipt_long',route('reimbursements')]] as $metric)<a href="{{ $metric[3] }}" class="rounded-2xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-muted">{{ $metric[0] }}</span><span class="material-symbols-outlined text-primary">{{ $metric[2] }}</span></div><p class="mt-3 text-2xl font-extrabold">{{ $metric[1] === null ? 'Unavailable' : number_format($metric[1]) }}</p><p class="mt-1 text-xs font-semibold text-primary">Open module →</p></a>@endforeach</section>
            <section class="max-w-3xl rounded-2xl bg-white p-5 shadow-sm"><div class="mb-5"><h2 class="flex items-center gap-2 text-xl font-bold"><span class="material-symbols-outlined text-primary">history</span>Recent Activity</h2><p class="mt-1 text-sm text-muted">Your latest business updates.</p></div>@if (count($dashboard['activity']))<div class="space-y-3">@foreach ($dashboard['activity'] as $item)<div class="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-primary">{{ $item[2] }}</span><div><strong class="block text-sm">{{ $item[0] }}</strong><span class="text-sm text-muted">{{ $item[1] }}</span></div></div>@endforeach</div>@else<span class="block rounded-xl bg-slate-50 p-5 text-sm text-muted">Recent activity will appear here when business records are available.</span>@endif</section>
        </main></div>
    <nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','point_of_sale','Sales'],['/products','inventory_2','Products'],['/customers','groups','Customers'],['/suppliers','local_shipping','Suppliers']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $loop->first ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav><script src="{{ asset('js/app.js') }}"></script>
</body>
</html>
