<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products · {{ config('app.name', 'EasyBiz') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',secondary:'#006c4a',canvas:'#faf8ff',muted:'#656b7e',danger:'#ba1a1a'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-slate-900 antialiased">
    @include('partials.business-directory')
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ url('/') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">EasyBiz</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['/','Home','home'],['/sales','Sales','shopping_cart'],['/products','Products','inventory_2'],['/customers','Customers','groups'],['/suppliers','Suppliers','local_shipping'],['/reimbursements','Reimbursements','receipt_long'],['/purchases','Purchases','shopping_cart'],['/reports','Reports','bar_chart']] as $item)<a href="{{ url($item[0]) }}" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold transition {{ $item[1] === 'Products' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>

    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between gap-4 border-b border-slate-200/70 bg-canvas/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div class="flex max-w-xl flex-1 items-center gap-3 rounded-xl bg-white px-4 py-2 shadow-sm"><span class="material-symbols-outlined text-muted">search</span><input id="global-search" type="search" placeholder="Search products, categories..." class="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"></div><div class="flex items-center gap-3"><div class="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:flex"><span class="material-symbols-outlined text-secondary">store</span>Maria's Store · Davao City</div><button type="button" class="relative flex h-10 w-10 items-center justify-center rounded-xl bg-white text-muted shadow-sm"><span class="material-symbols-outlined">notifications</span><span class="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-danger text-xs font-bold text-white">3</span></button></div></header>

        <main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">inventory_2</span><h1 class="text-3xl font-extrabold tracking-tight">Inventory &amp; Supplies</h1></div><p class="mt-2 text-base text-muted">Manage the products you sell, check stocks, and prevent shortages.</p></div><button type="button" onclick="showToast('Product registration form is ready for your next item.')" class="inline-flex h-14 items-center justify-center gap-3 rounded-xl bg-primary px-7 font-bold text-white shadow-md hover:bg-blue-700"><span class="material-symbols-outlined">add_circle</span>Add Product</button></div>

            <div class="mb-6 flex items-center gap-3 rounded-2xl border border-orange-200 bg-orange-50 p-4 text-orange-800"><span class="material-symbols-outlined rounded-xl bg-orange-100 p-2">warning</span><div class="flex-1"><p class="font-bold">3 products need restocking soon</p><p class="text-sm">Review low-stock items before your next delivery.</p></div><button type="button" onclick="filterLowStock()" class="rounded-xl bg-white px-4 py-2 text-sm font-bold shadow-sm hover:bg-orange-100">View 3 Low Items</button></div>

            <section class="mb-8 grid grid-cols-2 gap-3 md:grid-cols-4"><div class="rounded-2xl bg-primary p-5 text-white shadow-sm"><p class="text-sm font-semibold text-blue-100">All Items</p><p class="mt-1 text-3xl font-extrabold">125</p></div><div class="rounded-2xl bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-muted">In Stock</p><p class="mt-1 text-3xl font-extrabold text-secondary">114</p></div><div class="rounded-2xl bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-muted">Low Stock</p><p class="mt-1 text-3xl font-extrabold text-orange-600">8</p></div><div class="rounded-2xl bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-muted">Out of Stock</p><p class="mt-1 text-3xl font-extrabold text-danger">3</p></div></section>

            <section id="product-grid" class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                @foreach ([['Dry Grains','Rice 25kg','Premium Sinandomeng','₱1,250','12 sacks','Alerts trigger below 4 sacks','shelves','Healthy','emerald'],['Cooking Essentials','Cooking Oil 1L','Pure Coconut Oil','₱95','3 bottles','Alert set at 5 bottles (2 below minimum)','priority_high','Low Stock','orange'],['Baking & Pantry','Brown Sugar 1kg','Natural Cane Sugar','₱65','2 packs','Alert set at 10 packs (Critical level)','warning','Critical','red'],['Beverages','Instant Coffee','Twin Pack 3-in-1 Creamy','₱15','150 packs','Alerts trigger below 20 packs','local_cafe','Healthy','emerald'],['Canned Goods','Evaporated Milk','370ml Full Cream','₱38','0 cans left','Customers are requesting this item today','block','Out of Stock','red'],['Household','Dishwashing Liquid','Lemon Fresh 500ml','₱72','28 bottles','Alerts trigger below 8 bottles','cleaning_services','Healthy','emerald']] as $product)
                    <article class="product-card rounded-2xl bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md" data-search="{{ strtolower(implode(' ', $product)) }}" data-stock="{{ $product[8] }}"><div class="mb-5 flex items-start justify-between"><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-3 text-2xl text-primary">{{ $product[6] }}</span><div><p class="text-xs font-semibold uppercase tracking-wide text-muted">{{ $product[0] }}</p><h2 class="font-bold">{{ $product[1] }}</h2></div></div><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $product[8] === 'emerald' ? 'bg-emerald-100 text-secondary' : ($product[8] === 'orange' ? 'bg-orange-100 text-orange-800' : 'bg-red-100 text-danger') }}">{{ $product[7] }}</span></div><p class="text-sm text-muted">{{ $product[2] }}</p><div class="mt-4 flex items-end justify-between"><div><p class="text-2xl font-extrabold">{{ $product[3] }}</p><p class="text-xs text-muted">per unit</p></div><div class="text-right"><p class="text-xs font-semibold text-muted">Current Inventory</p><p class="font-bold {{ $product[8] === 'red' ? 'text-danger' : ($product[8] === 'orange' ? 'text-orange-700' : 'text-secondary') }}">{{ $product[4] }}</p></div></div><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-muted">{{ $product[5] }}</p><div class="mt-4 flex gap-2"><button type="button" onclick="showToast('Stock update opened for {{ $product[1] }}')" class="flex flex-1 items-center justify-center gap-1 rounded-xl bg-slate-100 py-2.5 text-sm font-bold hover:bg-slate-200"><span class="material-symbols-outlined text-lg">add</span>Add Stock</button><button type="button" onclick="showToast('Editing {{ $product[1] }}')" class="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-muted hover:text-primary" title="Edit product"><span class="material-symbols-outlined">edit</span></button></div></article>
                @endforeach
            </section>

            <section class="mt-8 rounded-2xl bg-slate-900 p-6 text-white"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm font-semibold text-blue-200">New item in store?</p><h2 class="mt-1 text-xl font-bold">Add wholesale snacks, beverages, or dry retail goods without complicated codes.</h2></div><button type="button" onclick="showToast('Product registration form is ready.')" class="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-primary hover:bg-blue-50"><span class="material-symbols-outlined">post_add</span>+ Register Product</button></div></section>
        </main></div>
    <nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','shopping_cart','Sales'],['/products','inventory_2','Products'],['#','receipt_long','Refunds'],['#','menu','More']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $item[2] === 'Products' ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav>
    <div id="toast" class="pointer-events-none fixed bottom-20 right-6 z-50 translate-y-24 rounded-xl bg-slate-900 px-5 py-3.5 text-sm font-semibold text-white opacity-0 shadow-xl transition-all lg:bottom-6"></div>
    <script src="{{ asset('js/app.js') }}"></script><script>function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.remove('translate-y-24','opacity-0');t.classList.add('translate-y-0','opacity-100');setTimeout(()=>{t.classList.add('translate-y-24','opacity-0');t.classList.remove('translate-y-0','opacity-100')},2500)}function filterLowStock(){document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('hidden',c.dataset.stock==='emerald'));showToast('Showing low-stock products')}document.getElementById('global-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('hidden',q&&!c.dataset.search.includes(q)))})</script>
</body>
</html>
