<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchases · {{ config('app.name', 'EasyBiz') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',secondary:'#006c4a',canvas:'#faf8ff',muted:'#656b7e',danger:'#ba1a1a'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-slate-900 antialiased">
    @include('partials.business-directory')
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ url('/') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">EasyBiz</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['/','Home','home'],['/sales','Sales','point_of_sale'],['/products','Products','inventory_2'],['/customers','Customers','groups'],['/suppliers','Suppliers','local_shipping'],['/reimbursements','Reimbursements','receipt_long'],['/purchases','Purchases','shopping_cart'],['/reports','Reports','analytics']] as $item)<a href="{{ url($item[0]) }}" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold transition {{ $item[1] === 'Purchases' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>
    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between gap-4 border-b border-slate-200/70 bg-canvas/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div class="flex max-w-xl flex-1 items-center gap-3 rounded-xl bg-white px-4 py-2 shadow-sm"><span class="material-symbols-outlined text-muted">search</span><input id="purchase-search" type="search" placeholder="Search purchase order, supplier, invoice..." class="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"></div><div class="flex items-center gap-3"><div class="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:flex"><span class="material-symbols-outlined text-secondary">storefront</span>Maria's Store · Davao City</div><button type="button" class="relative flex h-10 w-10 items-center justify-center rounded-xl bg-white text-muted shadow-sm"><span class="material-symbols-outlined">notifications</span><span class="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-danger text-xs font-bold text-white">3</span></button></div></header>
        <main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">shopping_cart</span><h1 class="text-3xl font-extrabold tracking-tight">Purchase Orders</h1></div><p class="mt-2 text-base text-muted">Manage inventory purchase orders, supplier deliveries, and invoice payments.</p></div><div class="flex gap-2"><button type="button" onclick="showToast('CSV export prepared.')" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 text-sm font-bold hover:bg-slate-200"><span class="material-symbols-outlined">file_download</span><span class="hidden sm:inline">Export CSV</span></button><button type="button" onclick="showToast('New purchase order form opened.')" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-white shadow-md hover:bg-blue-700"><span class="material-symbols-outlined">add</span>New Purchase Order</button></div></div>
            <section class="mb-8 grid grid-cols-1 gap-4 md:grid-cols-3">@foreach ([['Pending Orders','₱48,500.00','Committed value','orders','text-orange-700 bg-orange-100'],['Received This Month','₱162,400.00','Delivered & stocked','local_shipping','text-secondary bg-emerald-100'],['Unpaid Invoices','₱24,000.00','Open balance','schedule','text-danger bg-red-100']] as $stat)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-muted">{{ $stat[0] }}</p><p class="mt-1 text-3xl font-extrabold">{{ $stat[1] }}</p></div><span class="material-symbols-outlined rounded-xl p-3 {{ $stat[4] }}">{{ $stat[3] }}</span></div><p class="mt-5 text-sm font-semibold text-muted">{{ $stat[2] }}</p></article>@endforeach</section>
            <section class="mb-5 rounded-2xl bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div id="order-filters" class="flex flex-wrap gap-2">@foreach ([['all','All (24)'],['pending','Pending (4)'],['received','Received (18)'],['unpaid','Unpaid (2)']] as $filter)<button type="button" data-filter="{{ $filter[0] }}" class="order-filter rounded-xl px-4 py-2 text-sm font-bold {{ $loop->first ? 'bg-primary text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200' }}">{{ $filter[1] }}</button>@endforeach</div><select id="supplier-filter" class="rounded-xl border-0 bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-600 outline-none"><option value="all">All Suppliers</option><option>Universal Robina Corp.</option><option>San Miguel Foods Inc.</option><option>Mega Global Distribution</option><option>Alaska Milk Corp.</option><option>NutriAsia Corp.</option></select></div></section>
            <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="hidden grid-cols-12 gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-muted lg:grid"><span class="col-span-2">PO # &amp; Date</span><span class="col-span-2">Supplier</span><span class="col-span-3">Items</span><span class="col-span-2">Total Amount</span><span class="col-span-2">Payment Status</span><span>Actions</span></div><div id="order-list" class="divide-y divide-slate-100">@foreach ([['#PO-2026-089','Sep 15, 2026 · 09:30 AM','Universal Robina Corp.','15 cases Snacks & Candies','3 distinct SKUs','₱28,450.00','Net 30 terms','paid','Paid','View · Receive'],['#PO-2026-088','Sep 14, 2026 · 02:15 PM','San Miguel Foods Inc.','24 crates Dairy & Poultry','4 distinct SKUs','₱14,800.00','Bank Transfer','received','Print','Print'],['#PO-2026-087','Sep 12, 2026 · 11:00 AM','Mega Global Distribution','10 boxes Canned Sardines','2 distinct SKUs','₱36,200.00','Due in 5 days','pending','Partial 50%','Pay'],['#PO-2026-086','Sep 10, 2026 · 04:45 PM','Alaska Milk Corp.','50 packs Evaporated Milk','1 distinct SKU','₱9,650.00','Overdue','unpaid','Unpaid','Pay Now'],['#PO-2026-085','Sep 08, 2026 · 10:10 AM','NutriAsia Corp.','30 cases Condiments & Sauces','5 distinct SKUs','₱18,750.00','Cash on Delivery','received','Paid','Reorder']] as $order)<article class="purchase-row grid grid-cols-1 gap-3 px-5 py-4 transition hover:bg-slate-50 lg:grid-cols-12 lg:items-center lg:gap-4" data-status="{{ $order[7] }}" data-supplier="{{ $order[2] }}" data-search="{{ strtolower(implode(' ', $order)) }}"><div class="lg:col-span-2"><p class="text-sm font-bold">{{ $order[0] }}</p><p class="text-xs text-muted">{{ $order[1] }}</p><p class="mt-1 text-xs text-muted">Rep: Store purchasing</p></div><div class="text-sm font-bold lg:col-span-2">{{ $order[2] }}</div><div class="lg:col-span-3"><p class="text-sm font-semibold">{{ $order[3] }}</p><p class="text-xs text-muted">{{ $order[4] }}</p></div><div class="text-lg font-extrabold lg:col-span-2">{{ $order[5] }}</div><div class="lg:col-span-2"><p class="text-xs text-muted">{{ $order[6] }}</p><span class="mt-1 inline-flex rounded-full px-3 py-1 text-xs font-bold {{ $order[7] === 'paid' || $order[7] === 'received' ? 'bg-emerald-100 text-secondary' : ($order[7] === 'unpaid' ? 'bg-red-100 text-danger' : 'bg-orange-100 text-orange-800') }}">{{ $order[8] }}</span></div><div class="flex gap-2 lg:col-span-1"><button type="button" onclick="showToast('{{ $order[9] }}: {{ $order[0] }}')" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-primary hover:bg-blue-50">{{ $order[9] }}</button></div></article>@endforeach</div></section>
        </main></div>
    <nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','point_of_sale','Sales'],['/products','inventory_2','Products'],['/reimbursements','receipt_long','Refunds'],['/purchases','shopping_cart','Purchases']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $item[2] === 'Purchases' ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav>
    <div id="toast" class="pointer-events-none fixed bottom-20 right-6 z-50 translate-y-24 rounded-xl bg-slate-900 px-5 py-3.5 text-sm font-semibold text-white opacity-0 shadow-xl transition-all lg:bottom-6"></div><script src="{{ asset('js/app.js') }}"></script><script>function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.remove('translate-y-24','opacity-0');t.classList.add('translate-y-0','opacity-100');setTimeout(()=>{t.classList.add('translate-y-24','opacity-0');t.classList.remove('translate-y-0','opacity-100')},2500)}function applyFilters(){const q=document.getElementById('purchase-search').value.toLowerCase(),s=document.getElementById('supplier-filter').value,a=document.querySelector('.order-filter.bg-primary').dataset.filter;document.querySelectorAll('.purchase-row').forEach(r=>r.classList.toggle('hidden',(a!=='all'&&r.dataset.status!==a)||(s!=='all'&&r.dataset.supplier!==s)||(q&&!r.dataset.search.includes(q))))}document.querySelectorAll('.order-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.order-filter').forEach(x=>x.className='order-filter rounded-xl bg-slate-100 px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-200');b.className='order-filter rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white';applyFilters()}));document.getElementById('purchase-search').addEventListener('input',applyFilters);document.getElementById('supplier-filter').addEventListener('change',applyFilters)</script>
</body>
</html>
