<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reimbursements · {{ config('app.name', 'EasyBiz') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',secondary:'#006c4a',canvas:'#faf8ff',muted:'#656b7e',danger:'#ba1a1a'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-slate-900 antialiased">
    @include('partials.business-directory')
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ url('/') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">EasyBiz</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['/','Home','home'],['/sales','Sales','shopping_cart'],['/products','Products','inventory_2'],['/customers','Customers','groups'],['/suppliers','Suppliers','local_shipping'],['/reimbursements','Reimbursements','receipt_long'],['/purchases','Purchases','shopping_cart'],['/reports','Reports','bar_chart']] as $item)<a href="{{ url($item[0]) }}" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold transition {{ $item[1] === 'Reimbursements' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>

    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between gap-4 border-b border-slate-200/70 bg-canvas/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div class="flex max-w-xl flex-1 items-center gap-3 rounded-xl bg-white px-4 py-2 shadow-sm"><span class="material-symbols-outlined text-muted">search</span><input id="search-records" type="search" placeholder="Search claimant, reference, purpose..." class="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"></div><div class="flex items-center gap-3"><div class="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:flex"><span class="material-symbols-outlined text-secondary">store</span>Maria's Store · Davao City</div><button type="button" class="relative flex h-10 w-10 items-center justify-center rounded-xl bg-white text-muted shadow-sm"><span class="material-symbols-outlined">notifications</span><span class="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-danger text-xs font-bold text-white">3</span></button></div></header>

        <main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">receipt_long</span><h1 class="text-3xl font-extrabold tracking-tight">Reimbursements</h1></div><p class="mt-2 text-base text-muted">Track and pay back personal funds spent on store needs.</p></div><div class="flex gap-2"><button type="button" onclick="showToast('PDF summary prepared for download.')" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 text-sm font-bold hover:bg-slate-200"><span class="material-symbols-outlined">download</span><span class="hidden sm:inline">Download PDF Summary</span></button><button type="button" onclick="showToast('New reimbursement form opened.')" class="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-white shadow-md hover:bg-blue-700"><span class="material-symbols-outlined">add</span>New Reimbursement</button></div></div>

            <section class="mb-8 grid grid-cols-1 gap-4 md:grid-cols-3">@foreach ([['Pending Review','₱2,500','2 requests waiting','Action Required','text-orange-700 bg-orange-100'],['Ready to Pay','₱1,500','1 approved request','Approved','text-primary bg-blue-100'],['Settled This Month','₱5,200','8 requests paid','Completed','text-secondary bg-emerald-100']] as $stat)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-muted">{{ $stat[0] }}</p><p class="mt-1 text-3xl font-extrabold">{{ $stat[1] }}<span class="text-base font-normal text-muted">.00</span></p></div><span class="rounded-full px-3 py-1 text-xs font-bold {{ $stat[4] }}">{{ $stat[3] }}</span></div><p class="mt-5 text-sm font-semibold text-muted">{{ $stat[2] }}</p></article>@endforeach</section>

            <section class="mb-5 rounded-2xl bg-white p-4 shadow-sm"><div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div id="status-filters" class="flex flex-wrap gap-2">@foreach ([['all','All Records (11)'],['pending','Pending (2)'],['approved','Ready to Pay (1)'],['paid','Paid (8)']] as $filter)<button type="button" data-filter="{{ $filter[0] }}" class="status-filter rounded-xl px-4 py-2 text-sm font-bold {{ $loop->first ? 'bg-primary text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200' }}">{{ $filter[1] }}</button>@endforeach</div><div class="flex flex-wrap gap-2"><select id="category-filter" class="rounded-xl border-0 bg-slate-100 px-3 py-2 text-sm font-semibold text-slate-600 outline-none"><option value="all">All Categories</option><option>Transportation</option><option>Packaging</option><option>Store Supplies</option><option>Store Meals</option></select><select class="rounded-xl border-0 bg-slate-100 px-3 py-2 text-sm font-semibold text-slate-600 outline-none"><option>This Month (Sep 2026)</option><option>Last Month</option><option>Last 30 Days</option><option>Custom Range</option></select></div></div></section>

            <section class="overflow-hidden rounded-2xl bg-white shadow-sm"><div class="hidden grid-cols-12 gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-xs font-bold uppercase tracking-wide text-muted lg:grid"><span class="col-span-2">Date / Ref #</span><span class="col-span-2">Claimant</span><span class="col-span-3">Purpose</span><span class="col-span-2">Receipt</span><span>Amount</span><span>Status</span></div><div id="reimbursement-list" class="divide-y divide-slate-100">@foreach ([['Sep 15, 2026','#RMB-104','Juan dela Cruz','Transportation','Urgent trike fare to supplier depot for packaging boxes','View OR #4821','₱450.00','pending','Approve'],['Sep 14, 2026','#RMB-103','Maria Santos','Store Supplies','Emergency POS thermal receipt paper roll pack (10 pcs)','View OR #9932','₱650.00','approved','Mark as Paid'],['Sep 13, 2026','#RMB-102','Ricardo Reyes','Store Meals','Overtime staff dinner during annual store inventory count','View OR #1042','₱1,400.00','pending','Review'],['Sep 11, 2026','#RMB-101','Ana Lim','Maintenance','Replacement heavy-duty padlock and door latch for stockroom','View OR #7712','₱850.00','paid','Paid · GCash'],['Sep 08, 2026','#RMB-099','Lalamove','Transportation','Delivery fee for bulk sugar supplier transfer','View OR #3319','₱520.00','paid','Paid · Cash']] as $record)<article class="reimbursement-row grid grid-cols-1 gap-3 px-5 py-4 transition hover:bg-slate-50 lg:grid-cols-12 lg:items-center lg:gap-4" data-status="{{ $record[7] }}" data-search="{{ strtolower(implode(' ', $record)) }}" data-category="{{ $record[3] }}"><div class="lg:col-span-2"><p class="text-sm font-bold">{{ $record[0] }}</p><p class="text-xs text-muted">{{ $record[1] }}</p></div><div class="lg:col-span-2"><p class="text-sm font-bold">{{ $record[2] }}</p><p class="text-xs text-muted">{{ $record[3] }}</p></div><p class="text-sm text-muted lg:col-span-3">{{ $record[4] }}</p><a href="#" class="text-sm font-semibold text-primary hover:underline lg:col-span-2">{{ $record[5] }}</a><p class="text-lg font-extrabold lg:col-span-1">{{ $record[6] }}</p><div class="flex items-center justify-between gap-2 lg:col-span-2 lg:justify-end"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $record[7] === 'pending' ? 'bg-orange-100 text-orange-800' : ($record[7] === 'approved' ? 'bg-blue-100 text-primary' : 'bg-emerald-100 text-secondary') }}">{{ $record[8] }}</span>@if ($record[7] !== 'paid')<button type="button" onclick="showToast('{{ $record[8] }}: {{ $record[1] }}')" class="rounded-lg bg-slate-100 p-2 text-muted hover:text-primary" title="Update reimbursement"><span class="material-symbols-outlined text-lg">more_horiz</span></button>@endif</div></article>@endforeach</div></section>
        </main></div>
    <nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','shopping_cart','Sales'],['/products','inventory_2','Products'],['/reimbursements','receipt_long','Refunds'],['#','menu','More']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $item[2] === 'Refunds' ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav>
    <div id="toast" class="pointer-events-none fixed bottom-20 right-6 z-50 translate-y-24 rounded-xl bg-slate-900 px-5 py-3.5 text-sm font-semibold text-white opacity-0 shadow-xl transition-all lg:bottom-6"></div>
    <script src="{{ asset('js/app.js') }}"></script><script>function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.remove('translate-y-24','opacity-0');t.classList.add('translate-y-0','opacity-100');setTimeout(()=>{t.classList.add('translate-y-24','opacity-0');t.classList.remove('translate-y-0','opacity-100')},2500)}function applyFilters(){const q=document.getElementById('search-records').value.toLowerCase(),cat=document.getElementById('category-filter').value,active=document.querySelector('.status-filter.bg-primary').dataset.filter;document.querySelectorAll('.reimbursement-row').forEach(r=>r.classList.toggle('hidden',(active!=='all'&&r.dataset.status!==active)||(cat!=='all'&&r.dataset.category!==cat)||(q&&!r.dataset.search.includes(q))))}document.querySelectorAll('.status-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.status-filter').forEach(x=>x.className='status-filter rounded-xl bg-slate-100 px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-200');b.className='status-filter rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white';applyFilters()}));document.getElementById('search-records').addEventListener('input',applyFilters);document.getElementById('category-filter').addEventListener('change',applyFilters)</script>
</body>
</html>
