<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EasyBiz ERP - Monthly Store Summary</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root { color-scheme: light; }
        * { box-sizing: border-box; }
        body { margin: 0; background: #eef2f8; color: #182033; font-family: 'Plus Jakarta Sans', Arial, sans-serif; }
        .toolbar { display: flex; align-items: center; justify-content: space-between; gap: 1rem; max-width: 1020px; margin: 0 auto; padding: 1.25rem 1rem; }
        .toolbar a, .toolbar button { border: 0; border-radius: 10px; padding: .75rem 1rem; font: inherit; font-weight: 700; cursor: pointer; text-decoration: none; }
        .back { color: #4c5a72; background: transparent; } .print { color: #fff; background: #004ac6; } .pdf { color: #004ac6; background: #dbe7ff; }
        .toolbar-title { flex: 1; } .toolbar-title strong { display: block; font-size: 1.05rem; } .toolbar-title span { color: #6d7890; font-size: .8rem; }
        .paper { width: 210mm; min-height: 297mm; margin: 0 auto 2rem; padding: 16mm 18mm; background: #fff; box-shadow: 0 8px 35px rgba(28, 42, 67, .13); }
        .brand { display: flex; justify-content: space-between; gap: 2rem; border-bottom: 3px solid #004ac6; padding-bottom: 1rem; }
        .brand-mark { display: inline-flex; align-items: center; gap: .6rem; color: #004ac6; font-size: 1.4rem; font-weight: 800; } .mark { display: grid; place-items: center; width: 34px; height: 34px; border-radius: 9px; color: #fff; background: #004ac6; font-size: 1.1rem; }
        .eyebrow { margin: 0 0 .25rem; color: #69758b; font-size: .68rem; font-weight: 800; letter-spacing: .08em; text-transform: uppercase; } h1 { margin: 0; font-size: 1.35rem; } h2 { margin: 0; font-size: .9rem; } p { margin: .3rem 0; font-size: .73rem; line-height: 1.5; } .muted { color: #66738a; }
        .doc-meta { text-align: right; } .doc-meta strong { color: #004ac6; font-size: .9rem; }
        .section { margin-top: 1.25rem; } .section-title { display: flex; align-items: center; gap: .45rem; margin-bottom: .6rem; color: #004ac6; font-size: .78rem; font-weight: 800; text-transform: uppercase; letter-spacing: .05em; }
        .section-title::before { content: ''; width: 4px; height: 16px; border-radius: 3px; background: #004ac6; }
        .metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: .6rem; } .metric { padding: .75rem; border: 1px solid #dfe5ef; border-radius: 9px; } .metric .label { color: #637087; font-size: .65rem; font-weight: 700; } .metric .value { margin: .3rem 0; font-size: 1.15rem; font-weight: 800; } .metric .note { color: #637087; font-size: .62rem; }
        table { width: 100%; border-collapse: collapse; } th, td { padding: .48rem .4rem; border-bottom: 1px solid #e5e9f0; text-align: left; font-size: .68rem; vertical-align: top; } th { color: #637087; background: #f4f7fb; font-size: .62rem; text-transform: uppercase; } td.amount, th.amount { text-align: right; white-space: nowrap; } .positive { color: #006c4a; font-weight: 800; } .negative { color: #ba1a1a; }
        .two-col { display: grid; grid-template-columns: 1.3fr .7fr; gap: 1rem; } .rank-list, .week-list { display: grid; gap: .42rem; } .rank, .week { display: flex; align-items: center; justify-content: space-between; gap: .75rem; padding: .45rem .55rem; border-radius: 7px; background: #f6f8fc; } .rank-name { font-size: .67rem; font-weight: 700; } .rank-detail { color: #6b778b; font-size: .61rem; } .rank-value { color: #004ac6; font-size: .68rem; font-weight: 800; white-space: nowrap; }
        .recommendation { margin-top: .65rem; padding: .6rem .75rem; border-left: 3px solid #006c4a; border-radius: 5px; background: #e9f8f1; color: #285b48; font-size: .67rem; }
        .signatures { display: grid; grid-template-columns: 1fr 1fr; gap: 2rem; margin-top: 1.5rem; } .signature { padding-top: 1.3rem; border-top: 1px solid #aab4c4; } .signature strong { display: block; font-size: .7rem; } .signature span { color: #657188; font-size: .62rem; }
        .footer { margin-top: 1.25rem; padding-top: .7rem; border-top: 1px solid #dce2eb; text-align: center; color: #748095; font-size: .6rem; }
        @media (max-width: 850px) { .paper { width: calc(100% - 1rem); min-height: auto; padding: 1.25rem; } .brand { flex-direction: column; } .doc-meta { text-align: left; } .toolbar { flex-wrap: wrap; } .toolbar-title { order: -1; flex-basis: 100%; } }
        @page { size: A4 portrait; margin: 0; }
        @media print { body { width: 210mm; min-height: 297mm; background: #fff; } .toolbar { display: none; } .paper { width: 210mm; min-height: 297mm; margin: 0; box-shadow: none; page-break-after: always; } }
    </style>
</head>
<body>
    <div class="toolbar"><a href="{{ route('reports') }}" class="back">← Back to Reports</a><div class="toolbar-title"><strong>Print Preview: Store Summary Report</strong><span>A4 (210mm × 297mm) · September 2026</span></div><button type="button" class="pdf" onclick="window.print()">↓ Save as PDF</button><button type="button" class="print" onclick="window.print()">Print Document</button></div>
    <article class="paper">
        <header class="brand"><div><div class="brand-mark"><span class="mark">E</span> EasyBiz ERP</div><p class="eyebrow" style="margin-top:.65rem">Official Monthly Store Statement</p><h1>Maria's Store – Davao City</h1><p class="muted">Stall 14-B, Agdao Public Market, Davao City, 8000 Davao del Sur<br>TIN: 420-918-332-000 · Mobile: +63 917 892 4510</p></div><div class="doc-meta"><p class="eyebrow">Report Coverage</p><strong>September 1 – 30, 2026</strong><p class="muted" style="margin-top:.7rem"><b>Doc No:</b> RPT-2026-09-M<br><b>Printed:</b> Sep 30, 2026 · 6:15 PM</p></div></header>
        <section class="section"><div class="section-title">1. Month-at-a-Glance Cash Flow</div><div class="metrics"><div class="metric"><span class="label">Total Sales (Cash In)</span><div class="value">₱428,750.00</div><span class="note">From 1,248 daily counter transactions</span></div><div class="metric"><span class="label">Cost of Goods Purchased</span><div class="value">₱244,500.00</div><span class="note">Paid to beverage &amp; food distributors</span></div><div class="metric"><span class="label">Store Net Earnings</span><div class="value positive">₱98,420.00</div><span class="note">After supplier cost, utilities &amp; crew</span></div></div></section>
        <section class="section"><div class="section-title">2. Income &amp; Expense Reconciliation</div><table><thead><tr><th>Line Item / Category</th><th>Description / Notes</th><th class="amount">Amount (PHP)</th></tr></thead><tbody><tr><td><b>Gross Counter Sales</b></td><td class="muted">Retail sales (cash in drawer + QR Ph / GCash)</td><td class="amount positive">+₱428,750.00</td></tr><tr><td><b>Inventory Restock (Purchases)</b></td><td class="muted">Stock orders from URC, San Miguel, Mega Global, Alaska</td><td class="amount negative">-₱244,500.00</td></tr><tr><td><b>Store Staff Wages (2 helpers)</b></td><td class="muted">Semi-monthly bi-weekly payouts (Sep 15 &amp; Sep 30)</td><td class="amount negative">-₱32,000.00</td></tr><tr><td><b>Store Stall Rent &amp; Electric Bill</b></td><td class="muted">Market stall lease + chiller power</td><td class="amount negative">-₱33,830.00</td></tr><tr><td><b>Reimbursements &amp; Minor Supplies</b></td><td class="muted">Ice delivery, plastic bags, receipt rolls</td><td class="amount negative">-₱20,000.00</td></tr><tr><td colspan="2"><b>Net Store Income for September</b><br><span class="muted">Clean cash retained for Maria's personal savings</span></td><td class="amount positive"><b>₱98,420.00</b></td></tr></tbody></table></section>
        <section class="section"><div class="section-title">3. Top 5 Best-Selling Items</div><div class="two-col"><div class="rank-list">@foreach ([['San Miguel Pale Pilsen 330ml','1,420 bottles sold','₱71,000.00'],['Lucky Me! Pancit Canton (Calamansi)','890 packs sold','₱16,020.00'],['Mega Sardines in Tomato Sauce 155g','510 cans sold','₱12,750.00'],['Bear Brand Powdered Milk 33g','640 sachets sold','₱10,240.00'],['Great Taste White Coffee Twin Pack','580 packs sold','₱8,700.00']] as $item)<div class="rank"><div><span class="rank-name">{{ $loop->iteration }}. {{ $item[0] }}</span><br><span class="rank-detail">{{ $item[1] }}</span></div><span class="rank-value">{{ $item[2] }}</span></div>@endforeach</div><div><div class="section-title" style="margin-top:0">4. Weekly Sales Pattern</div><p class="muted">Average customer intake and peak revenue days:</p><div class="week-list"><div class="week"><b>Saturday (Peak Day ⭐)</b><span class="rank-value">₱24,200 / day</span></div><div class="week"><b>Sunday</b><span class="rank-value">₱19,800 / day</span></div><div class="week"><b>Friday Payday</b><span class="rank-value">₱18,500 / day</span></div><div class="week"><b>Mon–Thu Average</b><span class="rank-value">₱11,200 / day</span></div></div><div class="recommendation"><b>Recommendation:</b> Prepare extra fast-moving stock every Friday for the Saturday peak.</div></div></div></section>
        <div class="signatures"><div class="signature"><strong>Maria Santos</strong><span>Prepared By · Store Owner &amp; Operator</span></div><div class="signature"><strong>Ana Marie Lim</strong><span>Verified By · Senior Store Cashier</span></div></div>
        <footer class="footer"><b>EasyBiz ERP System Verification</b><br>HASH: 8F92-4C11-EB9B-2026 · No altered or clipped records.<br><br>EasyBiz ERP — Simple Small Business Management System<br>Page 1 of 1 · Official Printout Copy for Tax &amp; Business Record Filing</footer>
    </article>
</body>
</html>
