<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports · {{ config('app.name', 'ERP SYSTEM') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.googleapis.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',secondary:'#006c4a',canvas:'#faf8ff',muted:'#656b7e',danger:'#ba1a1a'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-slate-900 antialiased">
    @include('partials.business-directory')
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ url('/') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">ERP SYSTEM</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['/','Home','home'],['/sales','Sales','point_of_sale'],['/products','Products','inventory_2'],['/customers','Customers','groups'],['/suppliers','Suppliers','local_shipping'],['/reimbursements','Reimbursements','receipt_long'],['/purchases','Purchases','shopping_cart'],['/reports','Reports','analytics']] as $item)<a href="{{ url($item[0]) }}" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold transition {{ $item[1] === 'Reports' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-900' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>
    <div class="min-h-screen lg:pl-72"><header class="sticky top-0 z-30 flex h-20 items-center justify-between gap-4 border-b border-slate-200/70 bg-canvas/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><div class="flex max-w-xl flex-1 items-center gap-3 rounded-xl bg-white px-4 py-2 shadow-sm"><span class="material-symbols-outlined text-muted">search</span><input type="search" placeholder="Search reports..." class="w-full bg-transparent text-sm outline-none placeholder:text-slate-400"></div><div class="flex items-center gap-3"><div class="hidden items-center gap-2 rounded-xl bg-slate-100 px-3 py-2 text-sm font-semibold sm:flex"><span class="material-symbols-outlined text-secondary">storefront</span>Maria's Store · Davao City</div><button type="button" class="relative flex h-10 w-10 items-center justify-center rounded-xl bg-white text-muted shadow-sm"><span class="material-symbols-outlined">notifications</span><span class="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-danger text-xs font-bold text-white">3</span></button></div></header>
        <main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">analytics</span><h1 class="text-3xl font-extrabold tracking-tight">Store Reports &amp; Summary</h1></div><p class="mt-2 text-base text-muted">See how your store is doing this month in simple numbers.</p></div><div class="flex gap-2"><select class="h-12 rounded-xl border-0 bg-white px-4 text-sm font-bold text-slate-600 shadow-sm outline-none"><option>This Month (September 2026)</option><option>Last Month</option><option>Last 30 Days</option></select><a href="{{ route('reports.print') }}" class="inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-white shadow-md hover:bg-blue-700"><span class="material-symbols-outlined">print</span><span class="hidden sm:inline">Print Summary</span></a></div></div>
            <section class="mb-8 grid grid-cols-1 gap-4 lg:grid-cols-3">@foreach ([['Total Money In (Sales)','₱428,750.00','Good month (+14%)','payments','text-secondary bg-emerald-100','Money taken in from sales this month'],['What You Spent on Goods (Purchases)','₱244,500.00','Stock restocking & inventory orders','shopping_bag','text-primary bg-blue-100','Paid or owed to suppliers for store items'],['Estimated Money Left (Earnings)','₱98,420.00','Healthy store profit','savings','text-secondary bg-emerald-100','Money left after paying for goods & expenses']] as $stat)<article class="rounded-2xl bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-muted">{{ $stat[0] }}</p><p class="mt-1 text-3xl font-extrabold">{{ $stat[1] }}</p></div><span class="material-symbols-outlined rounded-xl p-3 {{ $stat[4] }}">{{ $stat[3] }}</span></div><p class="mt-5 text-sm font-bold text-secondary">{{ $stat[2] }}</p><p class="mt-1 text-xs text-muted">{{ $stat[5] }}</p></article>@endforeach</section>
            <div class="grid grid-cols-1 gap-6 xl:grid-cols-5"><section class="rounded-2xl bg-white p-5 shadow-sm xl:col-span-3"><div class="mb-6 flex items-center justify-between"><div><h2 class="flex items-center gap-2 text-xl font-bold">📅 Busiest Days of the Week</h2><p class="mt-1 text-sm text-muted">Which days bring the most customers and cash to your store</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-secondary">Live Pattern</span></div><div class="flex h-64 items-end justify-around gap-3 border-b border-slate-200 px-2">@foreach ([['Friday','₱18,500','h-32'],['Saturday','₱24,200','h-52'],['Sunday','₱19,800','h-40'],['Weekdays avg','₱11,200','h-24']] as $day)<div class="flex h-full flex-1 flex-col items-center justify-end gap-2"><span class="text-xs font-bold text-muted">{{ $day[1] }}</span><div class="w-full max-w-16 rounded-t-xl bg-primary transition hover:bg-blue-700 {{ $day[2] }}"></div><span class="text-xs font-semibold text-muted">{{ $day[0] }}</span></div>@endforeach</div><p class="mt-4 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-primary">⭐ Tip: Saturday is your strongest sales day. Consider stocking extra fast-moving items every Friday.</p></section>
                <section class="rounded-2xl bg-white p-5 shadow-sm xl:col-span-2"><div class="mb-5 flex items-center justify-between"><div><h2 class="flex items-center gap-2 text-xl font-bold">⭐ Top 5 Best-Selling Items</h2><p class="mt-1 text-sm text-muted">Fastest items off your shelves this month</p></div><span class="text-xs font-bold text-muted">September</span></div><div class="space-y-4">@foreach ([['San Miguel Pale Pilsen 330ml','1,420 bottles sold','₱71,000'],['Lucky Me! Pancit Canton','890 packs sold','₱16,020'],['Bear Brand Powdered Milk 33g','640 sachets sold','₱10,240'],['Great Taste White Coffee Twin Pack','580 packs sold','₱8,700'],['Mega Sardines in Tomato Sauce 155g','510 cans sold','₱12,750']] as $item)<div class="flex items-center justify-between gap-3"><div class="flex min-w-0 items-center gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-100 text-sm font-extrabold text-primary">{{ $loop->iteration }}</span><div class="min-w-0"><p class="truncate text-sm font-bold">{{ $item[0] }}</p><p class="text-xs text-muted">{{ $item[1] }}</p></div></div><strong class="whitespace-nowrap text-sm">{{ $item[2] }}</strong></div>@endforeach</div></section></div>
            <section class="mt-8"><div class="mb-4 flex items-center justify-between"><div><h2 class="flex items-center gap-2 text-xl font-bold">📄 Ready-to-Print Reports</h2><p class="mt-1 text-sm text-muted">Copies for your records, accountant, or family review.</p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-primary">3 Reports Ready</span></div><div class="grid grid-cols-1 gap-4 md:grid-cols-3">@foreach ([['Today\'s Daily Sales & Cash Count','Total cash in drawer, daily total, and receipts for today.','verified','Ready to print · Updated 6:00 PM'],['Monthly Income & Expense Summary','Simple list of total sales minus store supplies and operating costs.','calculate','Ready to print · Complete Month of September'],['Items to Reorder Soon (Low Stock)','Products running out this week so you do not run out of stock.','notification_important','12 items need restock before weekend']] as $report)<article class="rounded-2xl bg-white p-5 shadow-sm"><span class="material-symbols-outlined rounded-xl bg-slate-100 p-3 text-2xl text-primary">{{ $report[2] }}</span><h3 class="mt-4 font-bold">{{ $report[0] }}</h3><p class="mt-2 text-sm text-muted">{{ $report[1] }}</p><p class="mt-4 text-xs font-semibold text-secondary">{{ $report[3] }}</p><button type="button" onclick="window.print()" class="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-slate-100 py-2.5 text-sm font-bold text-primary hover:bg-blue-50"><span class="material-symbols-outlined text-lg">print</span>Print / PDF</button></article>@endforeach</div></section>
        </main></div>
    <nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','point_of_sale','Sales'],['/products','inventory_2','Products'],['/reimbursements','receipt_long','Refunds'],['/reports','bar_chart','Reports']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $item[2] === 'Reports' ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav><script src="{{ asset('js/app.js') }}"></script>
</body>
</html>
