<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sales · {{ config('app.name', 'ERP SYSTEM') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700;800&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{primary:'#004ac6',secondary:'#006c4a',canvas:'#faf8ff',muted:'#656b7e',danger:'#ba1a1a'},fontFamily:{sans:['Plus Jakarta Sans','sans-serif']}}}};</script>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="min-h-screen bg-canvas font-sans text-slate-900 antialiased">
    @include('partials.business-directory')
    @if (session('success'))<div class="fixed left-1/2 top-5 z-50 -translate-x-1/2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white shadow-lg">{{ session('success') }}</div>@endif
    <aside class="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col justify-between bg-white px-4 py-6 shadow-sm lg:flex"><div><a href="{{ route('home') }}" class="mb-8 flex items-center gap-3 px-3"><div class="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-xl font-extrabold text-white">E</div><div><p class="text-lg font-extrabold tracking-tight text-primary">ERP SYSTEM</p><p class="text-xs text-muted">Business dashboard</p></div></a><nav class="space-y-1" aria-label="Main navigation">@foreach ([['home','Home','home'],['sales','Sales','point_of_sale'],['products','Products','inventory_2'],['customers','Customers','groups'],['suppliers','Suppliers','local_shipping'],['reimbursements','Reimbursements','receipt_long'],['purchases','Purchases','shopping_cart'],['reports','Reports','analytics']] as $item)<a href="{{ route($item[0]) }}" class="flex min-h-11 items-center gap-3 rounded-xl px-4 text-sm font-semibold {{ $item[0] === 'sales' ? 'bg-primary text-white shadow-sm' : 'text-slate-500 hover:bg-slate-100' }}"><span class="material-symbols-outlined">{{ $item[2] }}</span>{{ $item[1] }}</a>@endforeach</nav></div><a href="#" class="flex min-h-12 items-center gap-3 rounded-xl px-4 text-sm font-semibold text-danger hover:bg-red-50"><span class="material-symbols-outlined">logout</span>Log Out</a></aside>
    <div class="min-h-screen lg:pl-72"><main class="mx-auto max-w-7xl px-4 py-8 pb-24 sm:px-6 lg:px-8 lg:pb-12"><div class="mb-8"><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-xl bg-blue-100 p-2 text-2xl text-primary">point_of_sale</span><h1 class="text-3xl font-extrabold tracking-tight">Sales</h1></div><p class="mt-2 text-base text-muted">Record and track your business sales with confidence.</p></div>
        @if ($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800">{{ $errors->first() }}</div>@endif
        <form id="sale-form" action="{{ route('sales.store') }}" method="POST" class="grid grid-cols-1 gap-6 xl:grid-cols-7">@csrf<input type="hidden" name="items" id="items-input"><section class="space-y-6 xl:col-span-4"><div class="rounded-2xl bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="flex items-center gap-2 text-lg font-bold"><span class="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-sm text-white">1</span>Who is buying?</h2><span class="text-xs font-semibold text-muted">Customer selection</span></div><div class="grid grid-cols-1 gap-2 sm:grid-cols-3">@foreach ([['Walk-in Customer','person_pin','Default customer'],['Juan Trading','storefront','Wholesale customer'],['Davao Grocers','store','Business customer']] as $customer)<button type="button" data-customer="{{ $customer[0] }}" class="customer-option rounded-xl p-3 text-left transition {{ $loop->first ? 'bg-primary text-white' : 'bg-slate-50 text-slate-700 hover:bg-blue-50' }}"><span class="material-symbols-outlined">{{ $customer[1] }}</span><span class="block text-sm font-bold">{{ $customer[0] }}</span><span class="block text-xs opacity-75">{{ $customer[2] }}</span></button>@endforeach</div><input type="hidden" id="customer" name="customer" value="Walk-in Customer"></div>
        <div class="rounded-2xl bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="flex items-center gap-2 text-lg font-bold"><span class="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-sm text-white">2</span>What did they buy?</h2><span class="text-xs font-bold text-secondary">Stock checked before sale</span></div><div class="flex items-center gap-2 rounded-xl bg-slate-50 px-4 py-3"><span class="material-symbols-outlined text-primary">search</span><input id="product-search" type="search" placeholder="Search product name..." class="w-full bg-transparent text-sm outline-none"></div><div id="product-list" class="mt-3 space-y-2">@foreach ([['Rice 25kg (Sinandomeng)',1250,24,'inventory_2'],['Cooking Oil 1L',185,24,'inventory_2'],['Instant Coffee Twin Pack',120,40,'local_cafe'],['Canned Sardines 155g',45,60,'inventory_2']] as $product)<div class="product-row flex items-center justify-between rounded-xl bg-slate-50 p-3" data-name="{{ strtolower($product[0]) }}"><div class="flex items-center gap-3"><span class="material-symbols-outlined rounded-lg bg-blue-100 p-2 text-primary">{{ $product[3] }}</span><div><p class="text-sm font-bold">{{ $product[0] }}</p><p class="text-xs text-muted">₱{{ number_format($product[1], 2) }} · In stock: {{ $product[2] }}</p></div></div><button type="button" class="add-product rounded-lg bg-blue-100 px-3 py-2 text-xs font-bold text-primary" data-name="{{ $product[0] }}" data-price="{{ $product[1] }}" data-stock="{{ $product[2] }}">Add</button></div>@endforeach</div></div></section>
        <aside class="h-fit space-y-6 xl:col-span-3"><div class="rounded-2xl bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="flex items-center gap-2 text-lg font-bold"><span class="material-symbols-outlined text-primary">receipt_long</span>Current Sale Cart</h2><span id="item-count" class="rounded-full bg-blue-100 px-2.5 py-1 text-xs font-bold text-primary">0 Items</span></div><div id="cart" class="space-y-2"><p id="empty-cart" class="rounded-xl bg-slate-50 p-4 text-sm text-muted">No products added yet.</p></div><div class="mt-4 space-y-2 border-t border-slate-200 pt-4 text-sm"><div class="flex justify-between text-muted"><span>Subtotal</span><strong id="subtotal" class="text-slate-900">₱0.00</strong></div><div class="flex justify-between text-muted"><span>VAT Included (12%)</span><span id="vat">₱0.00</span></div><div class="flex justify-between pt-2 text-base font-extrabold"><span>Total</span><strong id="total" class="text-primary">₱0.00</strong></div></div><button type="button" id="clear-cart" class="mt-4 w-full rounded-xl bg-slate-100 py-2.5 text-sm font-bold text-slate-600 hover:bg-slate-200">Clear Cart</button></div>
        <div class="rounded-2xl bg-white p-5 shadow-sm"><div class="mb-4 flex items-center justify-between"><h2 class="flex items-center gap-2 text-lg font-bold"><span class="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-sm text-white">3</span>How did they pay?</h2><span class="text-xs font-semibold text-muted">Payment &amp; status</span></div><div class="grid grid-cols-2 gap-2">@foreach ([['cash','payments','Cash'],['gcash','phone_iphone','GCash'],['bank','account_balance','Bank'],['card','credit_card','Card']] as $payment)<label class="payment-label flex cursor-pointer flex-col items-center gap-1 rounded-xl p-3 text-sm font-bold {{ $loop->first ? 'bg-primary text-white' : 'bg-slate-100 text-slate-700' }}"><input class="payment-option sr-only" type="radio" name="payment_method" value="{{ $payment[0] }}" data-payment="{{ $payment[0] }}" {{ $loop->first ? 'checked' : '' }}><span class="material-symbols-outlined">{{ $payment[1] }}</span>{{ $payment[2] }}</label>@endforeach</div><div id="cash-fields" class="mt-4"><label for="amount-received" class="mb-2 block text-sm font-semibold text-muted">Amount Received</label><input id="amount-received" name="amount_paid" type="number" min="0" step="0.01" placeholder="₱0.00" class="h-12 w-full rounded-xl border-0 bg-slate-100 px-4 text-sm font-semibold outline-none"><div class="mt-3 flex justify-between text-sm"><span class="text-muted">Change</span><strong id="change">₱0.00</strong></div></div><button id="complete-sale" type="submit" class="mt-5 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-secondary font-bold text-white hover:opacity-90"><span class="material-symbols-outlined">verified</span>Complete Sale</button></div></aside></form>
    </main></div><nav class="fixed inset-x-0 bottom-0 z-50 flex h-16 items-center justify-around bg-white shadow-lg lg:hidden">@foreach ([['/','home','Home'],['/sales','point_of_sale','Sales'],['/products','inventory_2','Products'],['/customers','groups','Customers'],['/suppliers','local_shipping','Suppliers']] as $item)<a href="{{ url($item[0]) }}" class="flex flex-col items-center gap-1 text-xs font-semibold {{ $item[1] === 'point_of_sale' ? 'text-primary' : 'text-muted' }}"><span class="material-symbols-outlined">{{ $item[1] }}</span>{{ $item[2] }}</a>@endforeach</nav>
    <script>
        const cart = [], money = value => '₱' + Number(value).toLocaleString('en-PH', {minimumFractionDigits: 2, maximumFractionDigits: 2});
        const cartElement = document.getElementById('cart'), itemsInput = document.getElementById('items-input');
        function renderCart() { cartElement.innerHTML = cart.length ? cart.map((item, index) => `<div class="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p class="text-sm font-bold">${item.name}</p><p class="text-xs text-muted">${item.quantity} × ${money(item.price)}</p></div><div class="flex items-center gap-2"><button type="button" data-index="${index}" data-change="-1" class="cart-change rounded-lg bg-white px-2 py-1 font-bold">−</button><strong>${money(item.price * item.quantity)}</strong><button type="button" data-index="${index}" data-change="1" class="cart-change rounded-lg bg-white px-2 py-1 font-bold">+</button><button type="button" data-remove="${index}" class="cart-remove ml-1 text-xs font-bold text-red-600">Remove</button></div></div>`).join('') : '<p class="rounded-xl bg-slate-50 p-4 text-sm text-muted">No products added yet.</p>'; const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0), vat = subtotal * 12 / 112; document.getElementById('item-count').textContent = cart.reduce((sum, item) => sum + item.quantity, 0) + ' Items'; document.getElementById('subtotal').textContent = money(subtotal); document.getElementById('vat').textContent = money(vat); document.getElementById('total').textContent = money(subtotal); itemsInput.value = JSON.stringify(cart); updateChange(); document.querySelectorAll('.cart-change').forEach(button => button.onclick = () => { const item = cart[button.dataset.index]; const next = item.quantity + Number(button.dataset.change); if (next > 0 && next <= item.stock) item.quantity = next; else if (next > item.stock) alert('Not enough stock available.'); renderCart(); }); document.querySelectorAll('.cart-remove').forEach(button => button.onclick = () => { cart.splice(button.dataset.remove, 1); renderCart(); }); }
        function updateChange() { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0), received = Number(document.getElementById('amount-received').value || 0); document.getElementById('change').textContent = money(Math.max(0, received - total)); }
        document.querySelectorAll('.add-product').forEach(button => button.onclick = () => { const item = cart.find(item => item.name === button.dataset.name); if (item) { if (item.quantity >= Number(button.dataset.stock)) return alert('Not enough stock available.'); item.quantity++; } else cart.push({name: button.dataset.name, price: Number(button.dataset.price), stock: Number(button.dataset.stock), quantity: 1}); renderCart(); });
        document.getElementById('product-search').oninput = event => { const query = event.target.value.toLowerCase(); document.querySelectorAll('.product-row').forEach(row => row.classList.toggle('hidden', !row.dataset.name.includes(query))); };
        document.getElementById('clear-cart').onclick = () => { cart.length = 0; renderCart(); };
        document.getElementById('amount-received').oninput = updateChange;
        document.querySelectorAll('.payment-option').forEach(input => input.onchange = () => { document.querySelectorAll('.payment-label').forEach(label => label.className = 'payment-label flex cursor-pointer flex-col items-center gap-1 rounded-xl bg-slate-100 p-3 text-sm font-bold text-slate-700'); input.closest('label').className = 'payment-label flex cursor-pointer flex-col items-center gap-1 rounded-xl bg-primary p-3 text-sm font-bold text-white'; document.getElementById('cash-fields').classList.toggle('hidden', input.value !== 'cash'); });
        document.getElementById('sale-form').onsubmit = event => { const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0), payment = document.querySelector('.payment-option:checked').value, received = Number(document.getElementById('amount-received').value || 0); if (!cart.length) { event.preventDefault(); alert('Please add at least one product.'); return; } if (payment === 'cash' && received < total) { event.preventDefault(); alert('Payment is not enough. Please enter the full amount.'); return; } const button = document.getElementById('complete-sale'); button.disabled = true; button.textContent = 'Completing Sale...'; };
    </script>
</body>
</html>
